version: '3.3'
services:
  db:
    image: registry.cn-hangzhou.aliyuncs.com/dounine/postgres:16.2-alpine3.19
    restart: always
    volumes:
      - /data/db:/var/lib/postgresql/data  # 数据库存储目录，默认创建在/data/postgres保存，请使用绝对位置。
    environment:
      - TZ=Asia/Shanghai  # 时区(其它时区请自行修改)
      - POSTGRES_DB=ipa-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=ROOTAbc123
  api:
    image: registry.cn-hangzhou.aliyuncs.com/dounine/ipa-api:latest
    restart: always
    depends_on:
      - db
    environment:
      - database_url=postgresql://root:ROOTAbc123@db:5432/ipa-db #帐号密码请与上面db服务一致，默认不会暴露到外部(安全)，如有需要请自行修改
      - domain=http://localhost:3000  # 对外访问地址，必需修改成自己的(https+域名 或者 公网IP+端口)(只能二选一)，例如修改成：(https://app.ipadump.com 或者 http://192.x.x.x:3000)，如果不使用https域名，将默认使用转发协议进行ipa安装，将提示《"app.ipadump.com"想要安装"xxx"》
      - TZ=Asia/Shanghai  # 时区(其它时区请自行修改)
      - log=error   # 日志级别(不要修改)
      - locale=zh-CN   # 默认语言(不要修改)
      - admin_username=admin   # 管理员账号(PS:请修改默认账号密码)
      - admin_password=admin   # 管理员密码(PS:请修改默认账号密码)
      - form_body_limit=10mb  # post body 限制(不要修改)
      - file_upload_block_size=5mb  # 文件上传分片大小(不建议修改)
      - ipa_file_limit=1gb    # ipa文件大小限制
      - clean_interval=1m    # 定时清理任务时间(不建议修改)
      - ipa_sign_file_expire=360m  # ipa签名过期时间,m分钟
      - ipa_file_save_time=60m   # ipa保存时间,无关联的ipa文件将被删除
      - ipa_file_temp_expire=60m  # ipa上传临时文件,超时将被删除
      - ipa_sign_storage_limit=10gb  # ipa签名存储总大小
      - ipa_sign_plugin_limit=10mb  # ipa签名插件限制大小
      - ipa_sign_plugin_count_limit=10  # ipa签名插件数量限制
      - ipa_icon_limit=5mb   # ipa图标大小限制
      - limit_per_millisecond=20   # 限流每20毫秒允许的请求一条,即每秒50条请求,1000/20=50
      - limit_burst_size=100    # 限流突发大小100条(当负载突然增加时，允许系统在短时间内处理更多请求，最多处理 100 个突发请求，然后回到平稳的每秒60个请求的速率。)
    volumes:
      - /data/app_file:/app/file  # ipa文件存储目录，默认创建在/data/app_file保存，请使用绝对位置。
      - /data/app_logs:/app/logs  # 日志存储目录，默认创建在/data/app_logs保存，请使用绝对位置。
    ports:
      - "3000:3000"  # 请根据实际情况修改冒号左边的端口，如有占用，请使用其它未使用的端口